import Link from "next/link";
import { ArrowRight, CalendarCheck2, Check, Clock3, LayoutDashboard, Route, Sparkles } from "lucide-react";
import { FaqExplorer } from "@/components/faq-explorer";
import { MarketingFooter, MarketingHeader } from "@/components/marketing-shell";
import { nicheList } from "@/lib/niches";

export default function Home() {
  return (
    <main className="landing-page landing-page--complete">
      <MarketingHeader />
      <section className="landing-hero landing-hero--split">
        <div className="landing-hero__copy"><p className="eyebrow">Agenda adaptativa para negócios de serviço</p><h1>Seu nicho.<br />Seu ritmo.<br /><em>Seu sistema.</em></h1><p>A Kronos transforma o modo como sua empresa atende em agenda, fluxo de trabalho e decisões claras — sem exigir que você monte tudo do zero.</p><div><Link className="button button--primary" href="/criar-conta">Criar meu espaço <ArrowRight size={17} /></Link><Link className="text-link" href="/demonstracao">Explorar demonstração <ArrowRight size={15} /></Link></div><small><Check size={14} /> Comece pelo nicho. Ajuste cada detalhe depois.</small></div>
        <div className="landing-product" aria-label="Prévia do produto Kronos"><header><span>CL</span><div><strong>Clima Prime</strong><small>Operação de hoje</small></div><em>10:24</em></header><div className="landing-product__metrics"><article><span>Agenda ocupada</span><strong>84%</strong><small>3 janelas livres</small></article><article><span>Em campo</span><strong>08</strong><small>2 técnicos disponíveis</small></article></div><section><p><Clock3 size={14} /> Próximos atendimentos</p>{[["10:30", "Maria Santos", "Instalação"], ["13:30", "Carlos Lima", "Reparo técnico"], ["15:30", "Ana Oliveira", "Orçamento"]].map(([time, client, service]) => <article key={time}><time>{time}</time><div><strong>{client}</strong><small>{service}</small></div><i /></article>)}</section><footer><Sparkles size={15} /><span>Agrupe quatro visitas por região amanhã.</span></footer></div>
      </section>
      <section className="landing-proof" id="recursos"><article><CalendarCheck2 /><strong>Agenda sem conflito</strong><span>Disponibilidade, duração, recursos e deslocamento no mesmo motor.</span></article><article><LayoutDashboard /><strong>Operação em um olhar</strong><span>Agenda, Kanban e indicadores usam a mesma fonte de dados.</span></article><article><Sparkles /><strong>Configuração por nicho</strong><span>Vocabulário, serviços e ideias coerentes com a sua rotina.</span></article></section>
      <section className="landing-story" id="como-funciona"><div><p className="eyebrow">Do cadastro ao primeiro atendimento</p><h2>A estrutura nasce da sua operação, não de um modelo genérico.</h2></div><ol><li><span>01</span><div><h3>Conte como você atende</h3><p>Nome, descrição, nicho, equipe, recursos e horários.</p></div></li><li><span>02</span><div><h3>Revise a configuração</h3><p>Cores, serviços, etapas do fluxo e conteúdos aparecem antes da ativação.</p></div></li><li><span>03</span><div><h3>Comece com uma base utilizável</h3><p>Cadastre clientes e horários. A agenda alimenta o restante do sistema.</p></div></li></ol></section>
      <section className="landing-niches" id="nichos"><header><div><p className="eyebrow">Seis pontos de partida</p><h2>Um produto. Vocabulários diferentes.</h2></div><p>Cada nicho recebe uma tabela de cores, serviços, etapas e perguntas iniciais próprias.</p></header><div>{nicheList.map((niche, index) => <article key={niche.id} style={{ "--niche-color": niche.theme.primary } as React.CSSProperties}><span>{String(index + 1).padStart(2, "0")}</span><h3>{niche.label}</h3><p>{niche.descriptor}</p><small>{niche.resource}</small></article>)}</div></section>
      <section className="landing-workflow"><article><Route size={22} /><p className="eyebrow">Coerência operacional</p><h2>Mover um atendimento atualiza a agenda e os indicadores.</h2><p>O sistema preserva uma fonte de verdade para evitar números diferentes em cada tela.</p><Link href="/demonstracao">Ver o fluxo configurado <ArrowRight size={16} /></Link></article><div>{["Agendado", "Em campo", "Aguardando peça", "Concluído"].map((stage, index) => <span key={stage}><i>{index + 1}</i>{stage}</span>)}</div></section>
      <section className="landing-faq"><header><div><p className="eyebrow">Perguntas antes de começar</p><h2>Entenda o funcionamento sem precisar marcar uma apresentação.</h2></div><Link href="/faq">Abrir central completa <ArrowRight size={16} /></Link></header><FaqExplorer compact /></section>
      <section className="landing-cta"><p className="eyebrow">Seu primeiro espaço</p><h2>Leve cinco minutos para configurar. Economize horas na operação.</h2><div><Link className="button button--primary" href="/criar-conta">Criar conta <ArrowRight size={17} /></Link><Link href="/entrar">Já tenho uma conta</Link></div></section>
      <MarketingFooter />
    </main>
  );
}
