"use client";

import { FormEvent, useActionState, useState } from "react";
import { Check, Mail, UserPlus, UsersRound } from "lucide-react";
import { inviteTeamMember, type ActionState } from "@/app/(workspace)/actions";
import { PageHeader } from "@/components/ui";

export type AccountPerson = { id: string; name: string; email?: string; role: string; status: "Ativo" | "Pendente" };
const initialState: ActionState = { status: "idle", message: "" };

export function AccountManager({ companyName, fullName, role, initialPeople, demo }: { companyName: string; fullName: string; role: string; initialPeople: AccountPerson[]; demo: boolean }) {
  const [people, setPeople] = useState(initialPeople);
  const [message, setMessage] = useState("");
  const [state, action, pending] = useActionState(inviteTeamMember, initialState);
  const inviteDemo = (event: FormEvent<HTMLFormElement>) => { if (!demo) return; event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get("email") ?? ""); const selectedRole = String(data.get("role") ?? "Profissional"); if (!email.includes("@")) { setMessage("Informe um e-mail válido."); return; } setPeople((current) => [...current, { id: crypto.randomUUID(), name: email.split("@")[0], email, role: roleLabel(selectedRole), status: "Pendente" }]); setMessage("Convite adicionado à demonstração."); event.currentTarget.reset(); };
  return <><PageHeader eyebrow="Conta · Pessoas" title="Conta e equipe" description={`Gerencie quem acessa ${companyName} e o que cada papel pode fazer.`} action={null} /><section className="account-overview"><article><span><UsersRound size={20} /></span><div><small>Espaço atual</small><strong>{companyName}</strong><p>{people.filter((person) => person.status === "Ativo").length} pessoas ativas</p></div></article><article><span>{fullName.split(" ").slice(0, 2).map((part) => part[0]).join("")}</span><div><small>Seu acesso</small><strong>{fullName}</strong><p>{role}</p></div></article></section><section className="account-grid"><div className="panel"><div className="section-heading"><h2>Equipe e convites</h2><span>{people.length}</span></div><div className="people-list">{people.map((person) => <article key={person.id}><span>{person.name.slice(0, 2).toUpperCase()}</span><div><strong>{person.name}</strong><small>{person.email ?? person.role}</small></div><em>{person.role}</em><i className={person.status === "Pendente" ? "pending" : ""}>{person.status}</i></article>)}</div></div><aside className="panel invite-panel"><UserPlus size={22} /><h2>Convidar alguém</h2><p>Escolha o menor nível de acesso necessário. O convite entra como pendente até o aceite.</p><form action={demo ? undefined : action} onSubmit={inviteDemo}><label className="field"><span>E-mail</span><input name="email" type="email" required placeholder="pessoa@empresa.com" /></label><label className="field"><span>Papel</span><select name="role" defaultValue="professional"><option value="admin">Administrador</option><option value="reception">Recepção</option><option value="professional">Profissional</option><option value="analyst">Analista</option></select></label><button className="button button--primary" disabled={pending}><Mail size={16} /> {pending ? "Registrando…" : "Registrar convite"}</button>{(message || state.message) ? <span className={`action-feedback action-feedback--${state.status === "error" ? "error" : "success"}`}>{message || state.message}</span> : null}</form></aside></section><section className="role-matrix"><header><p className="eyebrow">Estrutura de acesso</p><h2>O que cada conta pode enxergar.</h2></header>{[["Administrador", "Todas as páginas, equipe e configurações"], ["Recepção", "Agenda, atendimentos, clientes e conhecimento"], ["Profissional", "Própria agenda e atendimentos atribuídos"], ["Analista", "Dashboard e relatórios agregados"]].map(([name, access]) => <article key={name}><Check size={16} /><strong>{name}</strong><span>{access}</span></article>)}</section></>;
}

function roleLabel(value: string) { return { admin: "Administrador", reception: "Recepção", professional: "Profissional", analyst: "Analista" }[value] ?? value; }
