"use client";

import { useMemo, useState, useTransition } from "react";
import { ArrowRight, Check, Clock3, Sparkles, X } from "lucide-react";
import { updateRecommendation } from "@/app/(workspace)/actions";
import { useNiche } from "@/components/niche-provider";
import { PageHeader } from "@/components/ui";

export type InsightRow = { id: string; title: string; evidence: string; impact: string; origin: string; effort: string; status: "new" | "applied" | "dismissed" | "snoozed" };
export function InsightsManager({ initialInsights, demo }: { initialInsights: InsightRow[]; demo: boolean }) {
  const { niche } = useNiche(); const [insights, setInsights] = useState(initialInsights); const [tab, setTab] = useState<"new" | "applied" | "dismissed">("new"); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const visible = useMemo(() => insights.filter((item) => tab === "new" ? item.status === "new" || item.status === "snoozed" : item.status === tab), [insights, tab]);
  const change = (id: string, status: "applied" | "dismissed" | "snoozed") => { const before = insights; setInsights((current) => current.map((item) => item.id === id ? { ...item, status } : item)); if (demo) { setMessage(status === "applied" ? "Insight aplicado à demonstração." : status === "snoozed" ? "Você será lembrado depois." : "Insight dispensado."); return; } startTransition(async () => { const result = await updateRecommendation(id, status); setMessage(result.message); if (result.status === "error") setInsights(before); }); };
  return <><PageHeader eyebrow="Inteligência · Sob seu controle" title="Insights" description={`Sugestões explicadas a partir da sua operação e do modelo de ${niche.label.toLowerCase()}.`} action={null} /><div className="tabs"><button className={tab === "new" ? "active" : ""} onClick={() => setTab("new")}>Novos <span>{insights.filter((item) => item.status === "new" || item.status === "snoozed").length}</span></button><button className={tab === "applied" ? "active" : ""} onClick={() => setTab("applied")}>Aplicados</button><button className={tab === "dismissed" ? "active" : ""} onClick={() => setTab("dismissed")}>Dispensados</button></div>{message ? <div className="board-feedback" aria-live="polite">{pending ? "Atualizando…" : message}</div> : null}<section className="insights-list">{visible.length ? visible.map((insight, index) => <article key={insight.id}><div className="insight-index"><Sparkles size={18} /><span>{String(index + 1).padStart(2, "0")}</span></div><div className="insight-copy"><p>{index === 0 ? "OPORTUNIDADE" : index === 1 ? "PADRÃO IDENTIFICADO" : "AJUSTE SUGERIDO"}</p><h2>{insight.title}</h2><span>{insight.evidence}</span><div><small><strong>Impacto</strong>{insight.impact}</small><small><strong>Origem</strong>{insight.origin}</small><small><strong>Esforço</strong>{insight.effort}</small></div></div><aside>{tab === "new" ? <><button className="button button--primary" onClick={() => change(insight.id, "applied")}>Aplicar <ArrowRight size={16} /></button><button className="button button--ghost" onClick={() => change(insight.id, "snoozed")}><Clock3 size={15} /> Lembrar depois</button><button className="dismiss" onClick={() => change(insight.id, "dismissed")}><X size={14} /> Dispensar</button></> : <button className="button button--secondary" onClick={() => { setInsights((current) => current.map((item) => item.id === insight.id ? { ...item, status: "new" } : item)); setTab("new"); }}>Reabrir insight</button>}</aside></article>) : <div className="empty-state"><span><Check size={22} /></span><h3>Nenhum insight nesta lista</h3><p>As sugestões mudam de grupo conforme suas decisões.</p></div>}</section><p className="insight-note"><Check size={15} /> Nenhuma mudança é aplicada sem sua confirmação.</p></>;
}
