"use client";

import { Check, Copy, MessageCircle, Printer } from "lucide-react";
import { PixQrCode } from "@/components/pix-qr-code";

type Item = { id: string; description: string; quantity: number; unitPriceCents: number; totalCents: number };
export function ReceiptDocument({ receipt, items, organization }: { receipt: { number: string; customerName: string; customerDocument: string | null; serviceDescription: string; notes: string | null; totalCents: number; pixKey: string; pixPayload: string; issuedAt: string }; items: Item[]; organization: { name: string; description: string | null } }) {
  const copyPix = () => navigator.clipboard.writeText(receipt.pixPayload);
  const share = () => { const message = `Olá, ${receipt.customerName}. Segue o recibo ${receipt.number}, no valor de ${money(receipt.totalCents)}.\n\nPix copia e cola:\n${receipt.pixPayload}\n\nRecibo: ${location.href}`; window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); };
  return <main className="public-receipt-shell"><div className="public-receipt-actions" aria-label="Ações do recibo"><button onClick={() => window.print()}><Printer size={16} /> Imprimir ou salvar PDF</button><button onClick={copyPix}><Copy size={16} /> Copiar Pix</button><button onClick={share}><MessageCircle size={16} /> Enviar no WhatsApp</button></div><article className="receipt-paper"><header><div className="receipt-paper__brand"><span>K</span><div><strong>{organization.name}</strong><small>{organization.description || "Serviços profissionais"}</small></div></div><div><small>Recibo</small><strong>{receipt.number}</strong><span>{date(receipt.issuedAt)}</span></div></header><section className="receipt-paper__intro"><p>Recebemos de</p><h1>{receipt.customerName}</h1>{receipt.customerDocument ? <span>Documento: {receipt.customerDocument}</span> : null}<p>o valor de <strong>{money(receipt.totalCents)}</strong>, referente a {receipt.serviceDescription}.</p></section><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Valor unitário</th><th>Total</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td data-label="Item">{item.description}</td><td data-label="Quantidade">{number(item.quantity)}</td><td data-label="Valor unitário">{money(item.unitPriceCents)}</td><td data-label="Total">{money(item.totalCents)}</td></tr>)}</tbody><tfoot><tr><td colSpan={3}>Total do recibo</td><td>{money(receipt.totalCents)}</td></tr></tfoot></table>{receipt.notes ? <section className="receipt-paper__notes"><strong>Observações</strong><p>{receipt.notes}</p></section> : null}<section className="receipt-paper__pix"><div><small>Pagamento</small><h2>Pix no valor exato do recibo</h2><p>Abra o aplicativo do seu banco, escolha pagar com Pix e escaneie o código.</p><label><span>{receipt.pixKey}</span><button onClick={copyPix}><Copy size={14} /> Copiar código Pix</button></label></div><PixQrCode payload={receipt.pixPayload} /></section><footer><span><Check size={15} /> Documento emitido digitalmente pelo Kronos</span><small>A autenticidade pode ser conferida por este link exclusivo.</small></footer></article></main>;
}
function money(cents: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100); }
function number(value: number) { return new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 3 }).format(value); }
function date(value: string) { return new Intl.DateTimeFormat("pt-BR", { dateStyle: "long", timeZone: "America/Sao_Paulo" }).format(new Date(value)); }
