"use client";

import { FormEvent, useActionState, useState } from "react";
import { Bell, Check, Clock3, Columns3, LockKeyhole, Palette, RotateCcw, UsersRound } from "lucide-react";
import { saveOrganizationSettings, type ActionState } from "@/app/(workspace)/actions";
import { useNiche } from "@/components/niche-provider";
import { PageHeader } from "@/components/ui";
import { nicheList, type NicheId } from "@/lib/niches";

const tabs = ["Empresa e marca", "Nicho e modelos", "Agenda", "Equipe e acesso", "Notificações", "Kanban", "Segurança"] as const;
type Tab = typeof tabs[number];
const initialState: ActionState = { status: "idle", message: "" };

export function SettingsManager({ demo }: { demo: boolean }) {
  const { niche, nicheId, setNicheId, companyName, setCompanyName } = useNiche();
  const [tab, setTab] = useState<Tab>("Empresa e marca");
  const [message, setMessage] = useState("");
  const [notifications, setNotifications] = useState({ reminder24: true, reminder2: true, dailyDigest: false });
  const [state, action, pending] = useActionState(saveOrganizationSettings, initialState);
  const saveDemo = (event: FormEvent<HTMLFormElement>) => { if (!demo) return; event.preventDefault(); window.localStorage.setItem("kronos:settings", JSON.stringify({ companyName, nicheId, notifications })); setMessage("Configurações salvas nesta demonstração."); };
  const restore = () => { setNicheId("climatizacao"); setCompanyName("Clima Prime"); setMessage("Modelo original restaurado."); };
  return <><PageHeader eyebrow="Sistema · Personalização" title="Configurações" description="Ajuste a conta, a operação e as regras de acesso em um único lugar." action={null} /><section className="settings-layout"><nav>{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</nav><form action={demo ? undefined : action} onSubmit={saveDemo} className="settings-panel">{tab !== "Empresa e marca" ? <><input type="hidden" name="companyName" value={companyName} /><input type="hidden" name="nicheId" value={nicheId} /></> : null}
    {tab === "Empresa e marca" ? <><section><div className="settings-heading"><div><h2>Dados da empresa</h2><p>Informações exibidas no sistema e em comunicações.</p></div></div><div className="form-grid"><label className="field"><span>Nome da empresa</span><input name="companyName" value={companyName} onChange={(event) => setCompanyName(event.target.value)} /></label><label className="field"><span>Nicho atual</span><select name="nicheId" value={nicheId} onChange={(event) => setNicheId(event.target.value as NicheId)}>{nicheList.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div></section><section><div className="settings-heading"><div><h2>Tabela de cores</h2><p>As cores específicas de {niche.label.toLowerCase()} preservam contraste e reconhecimento.</p></div><span><Palette size={17} /> Modelo do nicho</span></div><div className="settings-swatches">{Object.entries(niche.theme).map(([name, color]) => <div key={name}><i style={{ background: color }} /><span>{name}</span><small>{color}</small></div>)}</div><div className="settings-note"><Check size={16} /><p><strong>Contraste aprovado</strong><span>Os controles e textos seguem a referência WCAG AA.</span></p></div></section></> : null}
    {tab === "Nicho e modelos" ? <SettingsSection icon={<Palette />} title={`Modelos de ${niche.label}`} text={`${niche.services.length} serviços, ${niche.workflow.length} etapas e ${niche.knowledge.length} artigos sugeridos.`}>{niche.services.map((service) => <label className="check-row" key={service.name}><input type="checkbox" defaultChecked /><span>{service.name}</span><small>{service.duration}</small></label>)}</SettingsSection> : null}
    {tab === "Agenda" ? <SettingsSection icon={<Clock3 />} title="Regras da agenda" text="Defina expediente, antecedência e intervalo de cancelamento."><div className="form-grid"><label className="field"><span>Início</span><input type="time" defaultValue="08:00" /></label><label className="field"><span>Fim</span><input type="time" defaultValue="18:00" /></label><label className="field"><span>Antecedência mínima</span><select defaultValue="60"><option value="0">Sem limite</option><option value="60">1 hora</option><option value="240">4 horas</option></select></label><label className="field"><span>Cancelamento online</span><select defaultValue="240"><option value="60">1 hora antes</option><option value="240">4 horas antes</option><option value="1440">1 dia antes</option></select></label></div></SettingsSection> : null}
    {tab === "Equipe e acesso" ? <SettingsSection icon={<UsersRound />} title="Papéis e permissões" text="Convites e pessoas são gerenciados na área Conta e equipe."><a className="button button--secondary" href="/conta">Abrir equipe</a></SettingsSection> : null}
    {tab === "Notificações" ? <SettingsSection icon={<Bell />} title="Lembretes" text="Escolha quais automações serão preparadas para cada agendamento."><Toggle label="Lembrete 24 horas antes" checked={notifications.reminder24} onChange={(checked) => setNotifications((value) => ({ ...value, reminder24: checked }))} /><Toggle label="Lembrete 2 horas antes" checked={notifications.reminder2} onChange={(checked) => setNotifications((value) => ({ ...value, reminder2: checked }))} /><Toggle label="Resumo diário da operação" checked={notifications.dailyDigest} onChange={(checked) => setNotifications((value) => ({ ...value, dailyDigest: checked }))} /></SettingsSection> : null}
    {tab === "Kanban" ? <SettingsSection icon={<Columns3 />} title="Etapas visíveis" text="A ordem reflete o modelo do nicho e continua ligada aos estados internos.">{niche.workflow.map((stage, index) => <label className="check-row" key={stage.name}><input type="checkbox" defaultChecked /><span>{stage.name}</span><small>Etapa {index + 1}</small></label>)}</SettingsSection> : null}
    {tab === "Segurança" ? <SettingsSection icon={<LockKeyhole />} title="Segurança da conta" text="Sessões, papéis e dados são isolados por organização."><div className="security-list"><p><Check size={15} /> Políticas de acesso por organização</p><p><Check size={15} /> Histórico de alterações operacionais</p><p><Check size={15} /> Recuperação segura de senha</p></div><a className="button button--secondary" href="/recuperar-senha">Redefinir minha senha</a></SettingsSection> : null}
    <footer><button type="button" className="button button--ghost" onClick={restore}><RotateCcw size={16} /> Restaurar modelo</button><button className="button button--primary" disabled={pending}>{pending ? "Salvando…" : "Salvar alterações"}</button>{(message || state.message) ? <span className={`action-feedback action-feedback--${state.status === "error" ? "error" : "success"}`}>{message || state.message}</span> : null}</footer>
  </form><aside className="settings-preview"><p className="eyebrow">PRÉVIA EM TEMPO REAL</p><div className="preview-card"><span>Hoje · 10:30</span><h3>Maria Santos</h3><p>{niche.services[0].name}</p><div><em>Confirmado</em><strong>{niche.services[0].duration}</strong></div></div><button className="button button--primary" type="button" disabled>Ação principal</button><small>A assinatura Kronos permanece constante.</small></aside></section></>;
}

function SettingsSection({ icon, title, text, children }: { icon: React.ReactNode; title: string; text: string; children: React.ReactNode }) { return <section className="settings-feature"><span>{icon}</span><div className="settings-heading"><div><h2>{title}</h2><p>{text}</p></div></div><div className="settings-feature__body">{children}</div></section>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
